---
- hosts: centos
  become: yes

  tasks:
  - name: Install Apache Service
    yum: 
      name: httpd
      state: present

  - name: Check Apache Is Running
    service:
      name: httpd
      state: started

  - name: Open port 80 http Firewall
    firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes

  - name: Copy Index File
    copy: src=./index.html dest=/var/www/html/index.html
