---
- hosts: linux
  become: yes

  tasks:
  - name: Update all packages on Red Hat family servers
    yum:
      name: "*"
      state: latest
    when: ansible_os_family == "RedHat"
    register: result_rh
  
  - name: Update all packages on Debian family servers
    apt:
      name: "*"
      state: latest
      update_cache: yes
    when: ansible_os_family == "Debian"
    register: result_deb

  - name: Reboot RH Servers
    reboot:
    when: result_rh.changed == "true" and ansible_os_family == "RedHat"
  
  - name: Reboot Debian Servers
    reboot:
    when: result_rh.changed == "true" and ansible_os_family == "Debian"
