---
- include_vars: /home/14piar09/ansible_mpfraga_taller2021/roles/hardening/vars/main.yml

- name: Install LAMP Stack
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages }}"

- name: Create VirtualHost Create
  template:
    src: /home/14piar09/ansible_mpfraga_taller2021/virtualhost.j2
    dest: /etc/httpd/conf.d/{{ site }}.conf
    mode: 0644
    owner: root
    group: root
  notify: restart apache

- name: Apache Server Started and Enabled
  service:
    name: httpd
    state: started
    enabled: yes

