---
- name: Install LAMP Stack
  yum:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages }}"

- name: Create VirtualHost Create
  template:
    src: /home/14piar09/ansible_mpfraga_taller2021/roles/hardening/templates/virtualhost.j2
    dest: /etc/httpd/conf.d/{{ site }}.conf
    mode: 0644
    owner: root
    group: root
  notify: restart apache

- name: Create Site directory
  file: 
    path: "{{ directory }}"
    state: directory
    owner: apache
    group: apache
    mode: 0644

- name: Copy index.html
  copy:
    src: ./templates/index.html
    dest: "{{ directory }}/index.html"
    owner: apache
    group: apache
    mode: 0644

- name: Add http to the firewall
  command: firewall-cmd --add-service=http --permanent
  notify: restart firewall

- name: Apache Server Started and Enabled
  service:
    name: httpd
    state: started
    enabled: yes

